---
- name: Get active network interface
  ansible.builtin.shell: "ip -o -4 route show to default | awk '{print $5}'"
  register: active_interface

- name: Rename the network interface to "net0"
  ansible.builtin.command: "ip link set dev {{ active_interface.stdout }} name net0"
  when: active_interface.stdout != "net0"
  notify: Restart networking

- name: Show information about the renamed interface
  ansible.builtin.command: ip addr show dev net0
  register: net0_info
  changed_when: active_interface.rc != 0

- name: Display the information about the renamed interface
  ansible.builtin.debug:
    msg: "{{ net0_info.stdout }}"
