---
- name: Install cryptsetup package
  ansible.builtin.apt:
    name: cryptsetup
    state: present
  when: ansible_os_family == "Debian"

- name: Install cryptsetup package
  ansible.builtin.dnf:
    name: cryptsetup
    state: present
  when: ansible_os_family == "RedHat"

- name: Check if the disk exists
  ansible.builtin.stat:
    path: "/dev/{{ disk_to_encrypt }}"
  register: disk_stat

- name: Fail if the disk does not exist
  ansible.builtin.fail:
    msg: "The disk {{ disk_to_encrypt }} does not exist."
  when: not disk_stat.stat.exists

- name: Encrypt the disk with LUKS
  community.crypto.luks_device:
    name: "/dev/{{ disk_to_encrypt }}"
    state: present
    passphrase: "{{ luks_passphrase }}"
  notify:
    - Open the encrypted disk
