---
- name: List all CPUs
  ansible.builtin.shell: |
    set -o pipefail
    lscpu | grep "^CPU(s):" | awk '{print $2}'
  register: cpu_list

- name: Check for Intel Hyper-Threading or AMD multithreading
  ansible.builtin.slurp:
    src: /sys/devices/system/cpu/smt/control
  register: ht_info_base64

- name: Show CPU information
  ansible.builtin.debug:
    msg: >
      System has {{ cpu_list.stdout }} CPU(s)
      Intel Hyper-Threading/AMD Multithreading is {{ ht_info_base64['content'] | b64decode }}
