---
- name: Update GRUB configuration to disable C-states
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_idle.max_cstate=0 processor.max_cstate=1"'
    state: present
    backrefs: true

- name: Update GRUB
  ansible.builtin.shell: /usr/sbin/update-grub
  args:
    warn: false

- name: Reboot the server to apply changes
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Switch CPU governor to performance mode
  ansible.builtin.shell: |
    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
      echo performance > $cpu
    done
  become: true
  register: cpu_governor
  changed_when: cpu_governor.rc != 0

- name: Apply changes to CPU governor
  ansible.builtin.command: cpupower frequency-set -g performance
  become: true
  register: cpu_power
  changed_when: cpu_power.rc != 0
